name: hitung_cepat
description: "Proyek Flutter baru."
# Mencegah paket dipublikasikan ke pub.dev secara tidak sengaja
publish_to: 'none' # Hapus baris ini jika Anda ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^4.0.0 # Paket untuk memilih file dari perangkat pengguna

  # Menambahkan font Cupertino Icons untuk ikon gaya iOS
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter # Paket untuk menjalankan pengujian Flutter

  # Paket lint untuk mendorong praktik pengkodean yang baik
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true # Menggunakan desain material untuk aplikasi

  assets:
    - assets/foto1.jpg
    - assets/foto2.jpg
    - assets/foto3.png
    - assets/foto4.jpg
    - assets/foto5.jpg
    - assets/foto6.jpg
    - assets/foto7.png
    - assets/foto8.png
    - assets/foto9.png
    - assets/foto10.jpg # Daftar aset gambar yang digunakan dalam aplikasi
